dist: trusty
addons:
  chrome: stable
language: node_js
install: npm ci
script:
    - npm run build:content:ci
    - npm run lint:ci
    - npm run test:ci
    - npm run e2e:ci
    - npm run build:ci
deploy:
    skip_cleanup: true
    keep_history: true
    provider: pages
    local_dir: www
    repo: ourchitecture/ourchitecture.github.com
    github_token: $GITHUB_TOKEN
    target_branch: master
    on:
        branch: master
