language: node_js
cache: npm
install: npm ci
jobs:
    include:
        - stage: test
          script: npm run lint:ci
        - script: npm run test:ci
        - script: npm run e2e:ci
        - stage: deploy
          provider: pages
          before_deploy: npm run build:ci
          skip_cleanup: true
          keep_history: true
          local_dir: www
          repo: ourchitecture/ourchitecture.github.com
          github_token: $GITHUB_TOKEN
          target_branch: master
          on:
              branch: master
