# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:latest-browsers

        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: npm ci
            - run:
                name: Build Content
                command: npm run build:content:ci
            - run:
                name: Code Analysis
                command: npm run lint:ci
            - run:
                name: Unit Testing
                command: npm run test:ci
            - run:
                name: End-to-End Testing
                command: npm run e2e:ci
            - run:
                name: Build
                command: npm run build:ci
            - persist_to_workspace:
                root: ./
                paths:
                    - www

    site-deploy:
        docker:
            - image: node:8.10.0
        steps:
            - checkout
            - attach_workspace:
                at: www
            - run:
                name: Setup Pages Deployment
                command: |
                    git config user.email "ci-build@ourchitecture.github.io"
                    git config user.name "ci-build"
            - run:
                name: Deploy docs to gh-pages branch
                command: npx gh-pages@2.0.1 -d www -r https://github.com/ourchitecture/ourchitecture.github.com -b master

workflows:
    version: 2
    build:
        jobs:
            - build
            - site-deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
